---

- name: "Check requested varaible to config microsoft R"
  assert: { that: "{{ item }} is defined" }
  with_items:
     - role_r_java_home

- name: "Configure Renviron"
  become: "true"
  template:
    src: "templates/r_environ.j2"
    dest: "{{ renviron_path }}"

