---

- name: "Check requested variable to install microsoft R"
  assert: { that: "{{ item }} is defined" }
  with_items:
   - role_r_binary
   - role_r_tmp_directory_installer
   - role_r_binary_archive_name

- name: "Ensure tmp directory to install R exist"
  become: "true"
  file:
    path: "{{ role_r_tmp_directory_installer }}"
    state: "directory"
    mode: "0755"

- name: "Get R binary"
  become: "true"
  get_url:
    url: "{{ role_r_binary.url }}"
    dest: "{{ role_r_tmp_directory_installer }}/"
    checksum: "{{ role_r_binary.checksum }}"

- name: "Unarchive R binary"
  become: "true"
  unarchive:
    src: "{{ role_r_tmp_directory_installer }}/{{ role_r_binary_archive_name }}"
    dest: "{{ role_r_tmp_directory_installer }}/"
    remote_src: "yes"

- name: "Install R engine"
  become: "true"
  command: "sh {{ role_r_tmp_directory_installer }}/{{ role_r_binary_directory_name }}/install.sh -u --accept-mkl-eula"

- name: "Install rpm R package system"
  become: "true"
  yum:
    name: "{{ item }}"
    state: "installed"
  with_items:
  - "{{ packageYum }}"

- name: "Clean tmp directory"
  become: "true"
  file:
    path: "{{ role_r_tmp_directory_installer }}"
    state: "absent"

