---

- name: "Install R engine"
  include: "install.yml"
  when: state in ["role_r_install", "role_r_whole_install"]

- name: "Config R engine"
  include: "config.yml"
  when: state in ["role_r_config", "role_r_whole_install"]

- name: "Update package"
  include: "package.yml"
  when: state in ["role_r_add_library", "role_r_update_library", "role_r_del_library"]

- name: "Remove R"
  include: "remove.yml"
  when: state in ["role_r_remove"]

