---

- name: "Check requested varaible to remove microsoft R"
  assert: { that: "{{ item }} is defined" }
  with_items:
   - role_r_package_microsoft

- name: "Remove R from YUM"
  become: "true"
  yum:
    name: "{{ item }}"
    state: "absent"
  with_items: "{{ role_r_package_microsoft }}"

- name: "Delete R directory"
  become: "true"
  file:
    path: "{{ role_r_directory }}"
    state: "absent"
